name: mlops-test
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Train my model'
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Train model
          pip install -r requirements.txt
          python model.py

          # Write to readme
          echo "## Model metrics" > report.md
          cat metrics.txt >> report.md
          
          cml-send-comment report.md
